name: "Test"
on:
  pull_request:

jobs:
  set-outputs:
    name: Set data output to mock WPT runner
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.mock-wpt.outputs.data }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - id: mock-wpt
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('.github/scripts/mock-wpt.js');
            script({ core });
  send-metrics:
    name: Send Metrics to Datadog
    runs-on: ubuntu-latest
    needs: set-outputs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - id: send-metrics
        uses: actions/github-script@v6
        inputs:
          data: ${{ needs.set-outputs.outputs.data }}
        with:
          script: |
            const script = require('.github/scripts/dd-reporter.js');
            script({ core });
